# TCL File Generated by Component Editor 23.1
# Wed Mar 11 23:01:56 GMT 2026
# DO NOT MODIFY


# 
# custom_fp_mul "custom_fp_mul" v1.0
#  2026.03.11.23:01:56
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module custom_fp_mul
# 
set_module_property DESCRIPTION ""
set_module_property NAME custom_fp_mul
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME custom_fp_mul
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL task7_ci_fp32_mul
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file task7_ci_fp32_mul.sv SYSTEM_VERILOG PATH ../task7_code/rtl/ci_step2/task7_ci_fp32_mul.sv TOP_LEVEL_FILE
add_fileset_file task7_fp_mul_ip_unit.sv SYSTEM_VERILOG PATH ../task7_code/rtl/core/task7_fp_mul_ip_unit.sv
add_fileset_file custom_fp_mul.qip OTHER PATH custom_fp_mul.qip


# 
# parameters
# 
add_parameter MUL_LATENCY INTEGER 2 ""
set_parameter_property MUL_LATENCY DEFAULT_VALUE 2
set_parameter_property MUL_LATENCY DISPLAY_NAME MUL_LATENCY
set_parameter_property MUL_LATENCY WIDTH ""
set_parameter_property MUL_LATENCY TYPE INTEGER
set_parameter_property MUL_LATENCY UNITS None
set_parameter_property MUL_LATENCY ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MUL_LATENCY DESCRIPTION ""
set_parameter_property MUL_LATENCY HDL_PARAMETER true


# 
# display items
# 


# 
# connection point ncs_cis0
# 
add_interface ncs_cis0 nios_custom_instruction end
set_interface_property ncs_cis0 clockCycle 0
set_interface_property ncs_cis0 operands 2
set_interface_property ncs_cis0 ENABLED true
set_interface_property ncs_cis0 EXPORT_OF ""
set_interface_property ncs_cis0 PORT_NAME_MAP ""
set_interface_property ncs_cis0 CMSIS_SVD_VARIABLES ""
set_interface_property ncs_cis0 SVD_ADDRESS_GROUP ""

add_interface_port ncs_cis0 dataa dataa Input 32
add_interface_port ncs_cis0 datab datab Input 32
add_interface_port ncs_cis0 result result Output 32
add_interface_port ncs_cis0 clk clk Input 1
add_interface_port ncs_cis0 clk_en clk_en Input 1
add_interface_port ncs_cis0 start start Input 1
add_interface_port ncs_cis0 reset reset Input 1
add_interface_port ncs_cis0 done done Output 1

