# TCL File Generated by Component Editor 23.1
# Sun Mar 15 13:07:41 GMT 2026
# DO NOT MODIFY


# 
# custom_f_accum_pipe "custom_f_accum_pipe" v1.0
#  2026.03.15.13:07:41
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module custom_f_accum_pipe
# 
set_module_property DESCRIPTION ""
set_module_property NAME custom_f_accum_pipe
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME custom_f_accum_pipe
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL task8_ci_fsum_pipe
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file custom_fp_add.qip OTHER PATH custom_fp_add.qip
add_fileset_file custom_fp_mul.qip OTHER PATH custom_fp_mul.qip
add_fileset_file task7_cordic_cos_multi_iter.sv SYSTEM_VERILOG PATH ../task7_code/rtl/core/task7_cordic_cos_multi_iter.sv
add_fileset_file task7_fp32_to_fx.sv SYSTEM_VERILOG PATH ../task7_code/rtl/core/task7_fp32_to_fx.sv
add_fileset_file task7_fp_add_ip_unit.sv SYSTEM_VERILOG PATH ../task7_code/rtl/core/task7_fp_add_ip_unit.sv
add_fileset_file task7_fp_mul_ip_unit.sv SYSTEM_VERILOG PATH ../task7_code/rtl/core/task7_fp_mul_ip_unit.sv
add_fileset_file task7_fx_to_fp32.sv SYSTEM_VERILOG PATH ../task7_code/rtl/core/task7_fx_to_fp32.sv
add_fileset_file task8_ci_fsum_pipe.sv SYSTEM_VERILOG PATH ../task7_code/rtl/task8_pipe/task8_ci_fsum_pipe.sv TOP_LEVEL_FILE
add_fileset_file task8_cordic_cos_pipe.sv SYSTEM_VERILOG PATH ../task7_code/rtl/task8_pipe/task8_cordic_cos_pipe.sv
add_fileset_file task8_fp_accum_interleaved.sv SYSTEM_VERILOG PATH ../task7_code/rtl/task8_pipe/task8_fp_accum_interleaved.sv
add_fileset_file task8_fp_add_rr_stage.sv SYSTEM_VERILOG PATH ../task7_code/rtl/task8_pipe/task8_fp_add_rr_stage.sv
add_fileset_file task8_fp_mul_rr_stage.sv SYSTEM_VERILOG PATH ../task7_code/rtl/task8_pipe/task8_fp_mul_rr_stage.sv
add_fileset_file task8_pipe_fsum_core.sv SYSTEM_VERILOG PATH ../task7_code/rtl/task8_pipe/task8_pipe_fsum_core.sv


# 
# parameters
# 
add_parameter FX_W INTEGER 40 ""
set_parameter_property FX_W DEFAULT_VALUE 40
set_parameter_property FX_W DISPLAY_NAME FX_W
set_parameter_property FX_W WIDTH ""
set_parameter_property FX_W TYPE INTEGER
set_parameter_property FX_W UNITS None
set_parameter_property FX_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property FX_W DESCRIPTION ""
set_parameter_property FX_W HDL_PARAMETER true
add_parameter FX_FRAC INTEGER 22 ""
set_parameter_property FX_FRAC DEFAULT_VALUE 22
set_parameter_property FX_FRAC DISPLAY_NAME FX_FRAC
set_parameter_property FX_FRAC WIDTH ""
set_parameter_property FX_FRAC TYPE INTEGER
set_parameter_property FX_FRAC UNITS None
set_parameter_property FX_FRAC ALLOWED_RANGES -2147483648:2147483647
set_parameter_property FX_FRAC DESCRIPTION ""
set_parameter_property FX_FRAC HDL_PARAMETER true
add_parameter CORDIC_W INTEGER 28 ""
set_parameter_property CORDIC_W DEFAULT_VALUE 28
set_parameter_property CORDIC_W DISPLAY_NAME CORDIC_W
set_parameter_property CORDIC_W WIDTH ""
set_parameter_property CORDIC_W TYPE INTEGER
set_parameter_property CORDIC_W UNITS None
set_parameter_property CORDIC_W ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CORDIC_W DESCRIPTION ""
set_parameter_property CORDIC_W HDL_PARAMETER true
add_parameter CORDIC_FRAC INTEGER 22 ""
set_parameter_property CORDIC_FRAC DEFAULT_VALUE 22
set_parameter_property CORDIC_FRAC DISPLAY_NAME CORDIC_FRAC
set_parameter_property CORDIC_FRAC WIDTH ""
set_parameter_property CORDIC_FRAC TYPE INTEGER
set_parameter_property CORDIC_FRAC UNITS None
set_parameter_property CORDIC_FRAC ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CORDIC_FRAC DESCRIPTION ""
set_parameter_property CORDIC_FRAC HDL_PARAMETER true
add_parameter CORDIC_ITER INTEGER 18 ""
set_parameter_property CORDIC_ITER DEFAULT_VALUE 18
set_parameter_property CORDIC_ITER DISPLAY_NAME CORDIC_ITER
set_parameter_property CORDIC_ITER WIDTH ""
set_parameter_property CORDIC_ITER TYPE INTEGER
set_parameter_property CORDIC_ITER UNITS None
set_parameter_property CORDIC_ITER ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CORDIC_ITER DESCRIPTION ""
set_parameter_property CORDIC_ITER HDL_PARAMETER true
add_parameter MUL_LATENCY INTEGER 3 ""
set_parameter_property MUL_LATENCY DEFAULT_VALUE 3
set_parameter_property MUL_LATENCY DISPLAY_NAME MUL_LATENCY
set_parameter_property MUL_LATENCY WIDTH ""
set_parameter_property MUL_LATENCY TYPE INTEGER
set_parameter_property MUL_LATENCY UNITS None
set_parameter_property MUL_LATENCY ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MUL_LATENCY DESCRIPTION ""
set_parameter_property MUL_LATENCY HDL_PARAMETER true
add_parameter ADD_LATENCY INTEGER 3 ""
set_parameter_property ADD_LATENCY DEFAULT_VALUE 3
set_parameter_property ADD_LATENCY DISPLAY_NAME ADD_LATENCY
set_parameter_property ADD_LATENCY WIDTH ""
set_parameter_property ADD_LATENCY TYPE INTEGER
set_parameter_property ADD_LATENCY UNITS None
set_parameter_property ADD_LATENCY ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ADD_LATENCY DESCRIPTION ""
set_parameter_property ADD_LATENCY HDL_PARAMETER true
add_parameter X3_FIFO_DEPTH INTEGER 32 ""
set_parameter_property X3_FIFO_DEPTH DEFAULT_VALUE 32
set_parameter_property X3_FIFO_DEPTH DISPLAY_NAME X3_FIFO_DEPTH
set_parameter_property X3_FIFO_DEPTH WIDTH ""
set_parameter_property X3_FIFO_DEPTH TYPE INTEGER
set_parameter_property X3_FIFO_DEPTH UNITS None
set_parameter_property X3_FIFO_DEPTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property X3_FIFO_DEPTH DESCRIPTION ""
set_parameter_property X3_FIFO_DEPTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point ncs_cis0
# 
add_interface ncs_cis0 nios_custom_instruction end
set_interface_property ncs_cis0 clockCycle 0
set_interface_property ncs_cis0 operands 2
set_interface_property ncs_cis0 ENABLED true
set_interface_property ncs_cis0 EXPORT_OF ""
set_interface_property ncs_cis0 PORT_NAME_MAP ""
set_interface_property ncs_cis0 CMSIS_SVD_VARIABLES ""
set_interface_property ncs_cis0 SVD_ADDRESS_GROUP ""

add_interface_port ncs_cis0 dataa dataa Input 32
add_interface_port ncs_cis0 datab datab Input 32
add_interface_port ncs_cis0 result result Output 32
add_interface_port ncs_cis0 clk clk Input 1
add_interface_port ncs_cis0 clk_en clk_en Input 1
add_interface_port ncs_cis0 start start Input 1
add_interface_port ncs_cis0 reset reset Input 1
add_interface_port ncs_cis0 done done Output 1
add_interface_port ncs_cis0 n n Input 8

